[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

